<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Inventory\Module'                          => __DIR__ . '/Module.php',
    'Inventory\Controller\InventoryController'  => __DIR__ . '/src/Inventory/Controller/InventoryController.php',
];
