<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Flight Booking System')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        Flight Booking System
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li <?php if ('/'. $CURRENT_ROUTE_NAME . '/' .$CURRENT_ACTION_NAME == $this->url('inventory', array('action' => 'add'))) echo 'class="active"'; ?>>
                            <a href="<?= $this->url('inventory', array('action' => 'add')) ?>">Add flight</a>
                        </li>
                        <li <?php if ('/'. $CURRENT_ROUTE_NAME . '/' .$CURRENT_ACTION_NAME == $this->url('inventory', array('action' => 'index'))) echo 'class="active"'; ?>>
                            <a href="<?= $this->url('inventory', array('action' => 'index')) ?>">Show flights</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>FBS 2016 by Vladyslav Semerenko.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
